# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    # Note: Do NOT bundle secrets (backend/.env or serviceAccountKey.json) into the executable.
    # Keep those files out of the built bundle and provide them separately to users.
    datas=[
        ('frontend/media', 'frontend/media'),
        ('extension', 'extension'),
        # If you need to include other non-secret data files, add them here.
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtNetwork',
        'flask',
        'flask.json',
        'werkzeug',
        'werkzeug.serving',
        'firebase_admin',
        'firebase_admin.credentials',
        'firebase_admin.firestore',
        'google.cloud.firestore',
        'google.cloud.firestore_v1',
        'google_auth_oauthlib',
        'google_auth_oauthlib.flow',
        'requests',
        'requests.adapters',
        'urllib3',
        'Pillow',
        'PIL.Image',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'whois',
        'tldextract',
        'backend',
        'backend.utils',
        'bs4',
        'lxml',
        'certifi',
        'OpenSSL',
        'cryptography',
        'frontend.system_tray_utils',
        'frontend.UI_helpers',
        'groq',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PySide2',
        'PySide6',
        'tkinter',
        'matplotlib.tests',
        'numpy.tests',
        'pytest',
        'IPython',
        'notebook',
        'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TrueWeb',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='frontend/media/icon-trueweb.ico',
)